### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by SiahRBLX** [boofiboi/FiveM-Discord-Presence#2] opened 2023-09-10 22:07 UTC
Location does not match what player is on via ingame

**Comment by boofiboi** [comment] 2023-09-11 06:40
Any screenshots of the issue? I unfortunatly wasnt able to reproduce it.

**Comment by SiahRBLX** [comment] 2023-09-11 06:51
Not home at the moment but when In the city the location don’t update via rich presence when players go to different streets.

I’ll try testing more around 6am EST

**Comment by boofiboi** [comment] 2023-09-11 11:29
I have a hunch what's going on. I'll get back to you when i also arrive home.

**Comment by Deathdomain** [comment] 2023-12-29 14:27
he didnt post anything but i will

**Comment by Deathdomain** [comment] 2023-12-29 14:27
https://cdn.discordapp.com/attachments/1070193725071962153/1190242597692776458/IMG_9934.png?ex=65a116cc&is=658ea1cc&hm=bfeec564bdc0c9db594493137348c491f5b6a73c43dada6f4fb3c028bca9539d&

**Comment by Deathdomain** [comment] 2023-12-29 14:28
https://cdn.discordapp.com/attachments/1070193725071962153/1190242287976976384/image.png?ex=65a11683&is=658ea183&hm=6c96de9bad90af94561153c08718200b4f637a34164ced96f1b45b880a6b9752&

**Comment by boofiboi** [comment] 2023-12-29 14:29
Perhaps im using the wrong export for getting the street location, lemme find it.

**Comment by Deathdomain** [comment] 2023-12-29 14:30
okay, i just got mine from you last night :) easy to set up just want the street to show since its the only preset working for me

**Comment by boofiboi** [comment] 2023-12-29 14:32
`function location()
    local coords = GetEntityCoords(ped)
    local location = GetStreetNameFromHashKey(GetStreetNameAtCoord(coords[1], coords[2], coords[3]))
    local hash = GetStreetNameFromHashKey(location)
    return Config.LocationText .. ' ' .. hash
end
`


Could you try replacing the location() function with this and testing it?

**Comment by Deathdomain** [comment] 2023-12-29 14:41
> function location()

that would be where? server or client?

**Comment by boofiboi** [comment] 2023-12-29 14:41
Also,

Does the script always output Spanish Ave, or does it start where you are but not update?
Because if so, I can fix this right now without the game installed.

**Comment by Deathdomain** [comment] 2023-12-29 14:41
> Also,
> 
> Does the script always output Spanish Ave, or does it start where you are but not update? Because if so, I can fix this right now without the game installed.

spanish 24/7

**Comment by boofiboi** [comment] 2023-12-29 14:42
> > function location()
> 
> that would be where? server or client?

[client.lua line 57](https://github.com/boofiboi/FiveM-Discord-Presence/blob/main/client/client.lua)

**Comment by Deathdomain** [comment] 2023-12-29 14:44
> > > function location()
> > 
> > 
> > that would be where? server or client?
> 
> [client.lua line 57](https://github.com/boofiboi/FiveM-Discord-Presence/blob/main/client/client.lua)

restarting now and testing

**Comment by Deathdomain** [comment] 2023-12-29 14:48
![image](https://github.com/boofiboi/FiveM-Discord-Presence/assets/130054177/a3add336-ca77-4757-8a5f-b48c1d41966d)

**Comment by boofiboi** [comment] 2023-12-29 14:49
Any errors on the client side in the console?

**Comment by Deathdomain** [comment] 2023-12-29 14:50
> Any errors on the client side in the console?

no errors in F8 or in my console for VPN or TxAdmin

**Comment by boofiboi** [comment] 2023-12-29 14:51
> > Any errors on the client side in the console?
> 
> no errors in F8 or in my console for VPN or TxAdmin

Any errors on the **client side console?**

**Comment by Deathdomain** [comment] 2023-12-29 14:52
> > > Any errors on the client side in the console?
> > 
> > 
> > no errors in F8 or in my console for VPN or TxAdmin
> 
> Any errors on the **client side console?** (F8 in game)

No Errors in F8

**Comment by boofiboi** [comment] 2023-12-29 15:00
Hmmm, try replacing the function with this:

```
function location()
    local coords = GetEntityCoords(ped)
    local streethash = GetStreetNameAtCoord(coords)
    local streetname = GetStreetNameFromHashKey(streethash)
    return Config.LocationText .. ' ' .. streetname
end
```

**Comment by Deathdomain** [comment] 2023-12-29 15:11
> Hmmm, try replacing the function with this:
> 
> ```
> function location()
>     local coords = GetEntityCoords(ped)
>     local streethash = GetStreetNameAtCoord(coords.x, coords.y, coords.z)
>     local streetname = GetStreetNameFromHashKey(streethash)
>     return Config.LocationText .. ' ' .. streetname
> end
> ```

![image](https://github.com/boofiboi/FiveM-Discord-Presence/assets/130054177/3ef13ee5-f9a7-4c32-b408-7fdbbefc20a5)

**Comment by boofiboi** [comment] 2023-12-29 15:14
Change
`GetStreetNameAtCoord(coords.x, coords.y, coords.z)`
to 
`GetStreetNameAtCoord(coords)`


I genuinely have 0 clue right now how the coords works and how to parse them. I haven't used LUA in almost half a year.

**Comment by Deathdomain** [comment] 2023-12-29 15:21
damn, might need to find another one huh?

**Comment by boofiboi** [comment] 2023-12-29 15:22
I'll get around to installing it again and trying this out.
Tommorow ill check back for more here.

**Comment by Deathdomain** [comment] 2023-12-29 15:27
damn alright, ill revert back to the base one so my stuff shows up for now, might look for another and come back tomorrow for the fix :)

**Comment by boofiboi** [comment] 2023-12-29 15:29
> damn alright, ill revert back to the base one so my stuff shows up for now, might look for another and come back tomorrow for the fix :)

You could also try suggesting any new presets, im bone dry on ideas.

**Comment by Deathdomain** [comment] 2023-12-29 15:33
i just wanted the Street name and Number of players in the city showing so the preset you had i was really vibing for :D

**Comment by Deathdomain** [comment] 2023-12-31 17:25
> > damn alright, ill revert back to the base one so my stuff shows up for now, might look for another and come back tomorrow for the fix :)
> 
> You could also try suggesting any new presets, im bone dry on ideas.

anything yet?

**Comment by boofiboi** [comment] 2023-12-31 17:36
I'm still working on it, seems im either using the natives wrong, or im doing smth else wrong.

**Comment by boofiboi** [comment] 2023-12-31 18:12
Pushed a fix [here](https://github.com/boofiboi/FiveM-Discord-Presence/commit/7da66b891927093e7b6022ec26ebe2ccd2686155)

It does indeed turn out i am an idiot.
It was a single word that was wrong.

**Comment by boofiboi** [comment] 2023-12-31 18:15
I've reopened the issue, as I found a separate bug that correlates to this one.
Also, still open for discussion if it still doesn't work.

**Comment by boofiboi** [comment] 2024-01-05 20:28
It was a local issue and i forgot to close this one, im dumb.

**Closed by boofiboi** 2024-01-05 20:28 UTC
